name: halo_dart
description: >-
  Personal dart tools
version: 0.0.6
homepage: https://github.com/halowang/halo_dart

environment:
  sdk: '>=2.18.4 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
